### ISSUE TITLE
Sécurisation plus intuitive

### ISSUE THREAD

**Issue by real34** [lachouettecoop/participation#21]
**TL;DR:** 3 pistes

- pas de mot de passe depuis le réseau local (creuser avec Traefik)
- ajouter le login/pass en mémoire (et invisible) sur le PC de l’acceuil (ou en visible, avec une url `https://user:password@participation.lachouettecoop.fr` dans le favori)
- test de solution comme https://www.npmjs.com/package/staticrypt pour chiffrer les pages statiques avec un mot de passe plus convivial

---

> Au niveau sécurisation, je me suis rendu compte que le mot de passe posait problème. Il me faut regarder mais une solution serait peut être de ne pas demander le mot de passe pour les ordinateurs sur le réseau du Lab.

Pour les problèmes, voir : https://lachouettecoop.zulipchat.com/#narrow/stream/174627-Grp--.20Informatique/topic/Acc.C3.A8s.20r.C3.A9seau.20-.20probl.C3.A8me/near/161367012

> Nous n’avons pas réussi
Nos identifiants perso ne fonctionnaient pas. Y a t il un identifiant général qu’il faudrait mettre à portée ou rajouter dans le dossier du grand hibou?
Selon les cartes scannées le système a fonctionné.
Sur certaine le scan fonctionnait mais n’affichait pas le futur taf
Sur d’autres le message d’erreur comme envoyé sur la photo
Bonne journée

**Comment by real34** [comment]
Pour la solution via traefik cela ne semble pas possible d’après mes essais, et https://github.com/containous/traefik/issues/2260

… en tout cas je ne suis pas parvenu à le faire fonctionner. Le but serait de whitelister l’IP du Lab (aucun mot de passe demandé), tout en laissant le prompt pour les autres IPs.

@remi-filament est-ce que tu connais un moyen d’atteindre cela avec Traefik ?

Je commencerai donc à regarder les alternatives.

**Comment by remi-filament** [comment]
Effectivement ça ne semble pas possible.
Le plus simple serait peut-être d'ajouter un nginx entre traefik et l'app (comme c'est fait pour enjolras ou adminchouettos) qui porterait l'authentification en fonction de l'IP ?

**Comment by real34** [comment]
J’ai testé chez moi, et je pense que remplacer l’url dans le bookmark de l’ordi d’accueil serait le plus simple et moins prise de tête en l’état.

https://user:password@participation.lachouettecoop.fr au lieu de https://participation.lachouettecoop.fr et basta…

À voir si quelqu’un peut essayer durant un hackathon !

**Comment by real34** [comment]
J’ai effectué cette opération sur le PC de l’accueil.
Ainsi en cliquant sur le favori, seul le message ci-dessous apparaît :

![lab-connexion](https://user-images.githubusercontent.com/75968/56512727-82df0400-6530-11e9-8f44-080f5a31c398.png)
