### ISSUE TITLE
Envoi des demandes par email plutôt que sur Zulip

### ISSUE THREAD

**Issue by real34** [lachouettecoop/participation#38]
CR du 16/04/2020 et 04/05/2020

> Par souci de confidentialité, les demandes de Chouettos (GH ou non) devront être traitées via l’adresse mail bureau-des-membres@lachouettecoop.fr. Ainsi, il est décidé d’arrêter l’envoi des demandes des Chouettos faites depuis l’outil “Information sur la participation” vers Zulip. Cet envoi est donc à rediriger vers le mail bureau-des-membres@lachouettecoop.fr.

**Comment by FabriceLCC** [comment]
Hé coucou. Super ça fonctionne, nous avons bien reçu le message sur l'adresse du bureau des membres. Merci Pierre et Antoine pour le briefing sur github :)
